services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FASTAPI_SERVER_ADDR=backend:9091
    command: >
      /bin/sh -c "envsubst '\$${FASTAPI_SERVER_ADDR}' < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - backend

  backend:
    build:
      context: fastapi
      target: builder
    stop_signal: SIGINT
    env_file:
      - .env
    volumes:
      - ./fastapi:/app
    ports:
      - "9091:9091"